export const LOAD_ALL_SUCCEEDED = 'clothesTemperatureMapping-list/LOAD_ALL_SUCCEEDED'
export const CHANGE_NEW_MIN_TEMP = 'clothesTemperatureMapping-list/CHANGE_NEW_MIN_TEMP'
export const CHANGE_NEW_MAX_TEMP = 'clothesTemperatureMapping-list/CHANGE_NEW_MAX_TEMP'
export const CHANGE_NEW_SET_OF_CLOTHES = 'clothesTemperatureMapping-list/CHANGE_NEW_SET_OF_CLOTHES'
export const ADD_MAPPING_REQUESTED = 'clothesTemperatureMapping-list/ADD_MAPPING_REQUESTED'
export const ADD_MAPPING_SUCCEEDED = 'clothesTemperatureMapping-list/ADD_MAPPING_SUCCEEDED'
export const DELETE_CLOTHES_TEMPERATURE_MAPPING = 'clothesTemperatureMapping-list/DELETE_CLOTHES_TEMPERATURE_MAPPING'
